config/routes.rb
Rails.application.routes.draw do
  get 'persona/index'

  devise_for :usuarios, controllers: {registrations: 'registrations'}
  get 'welcome/index'

  root to: 'home#index'

  

  
  get 'home/buscar_canchas' => 'home#buscar_canchas', as: :buscar_canchas
  
  post 'comentario/create'
  
  resources :local
  resources :cancha
  resources :servicio
  resources :publicidad
  resources :home
  resources :persona
  resources :alquiler
  
  
  
  post 'alquiler/buscar'=> 'alquiler#index', as: :buscar
  put 'alquiler/confirmar/:id(.:format)'=> 'alquiler#confirmar', as: :confirmar
  
  get 'home/:id/reservar'=> 'home#reservar', as: :reservar
  get 'home/:id/alquilar'=> 'home#alquilar', as: :alquilar
 

end

app/models/alquiler.rb
 class Alquiler < ActiveRecord::Base
     self.table_name = "alquileres"
     #belongs_to :cancha
     belongs_to :cancha, :class_name => "Cancha", :foreign_key => "canchas_id"
     has_many :alquiler_servicios
     
      
     validates :fecha, presence: true
     validates :hora_inicio, presence: true
     validates :hora_fin, presence: true
     validates :canchas_id, presence: true
      
 end

app/models/alquiler_servicio.rb
 class AlquilerServicio < ActiveRecord::Base
     self.table_name = "alquileres_servicios"
     belongs_to :alquiler
     
      
     validates :alquileres_id, presence: true
     validates :usuarios_id, presence: true
     validates :servicios_id, presence: true
      
 end

app/models/cancha.rb
 class Cancha < ActiveRecord::Base
     mount_uploader :foto, FotoUploader
     
     belongs_to :local, :class_name => "Local", :foreign_key => "locales_id"
     belongs_to :tipo_tarifa, :class_name => "TipoTarifa", :foreign_key => "tipo_tarifas_id"
     has_many :alquileres, :class_name => "Alquiler", :foreign_key => "canchas_id"
     has_many :comentarios, :class_name => "Comentario", :foreign_key => "canchas_id"
     
     
    
     
     
     
      
     validates :descripcion, presence: true
     validates :locales_id, presence: true
     validates :tipo_tarifas_id, presence: true
     validates :hora_de, presence: true
     validates :hora_hasta, presence: true
     validates :importe_tarifa, presence: true
      
 end

app/models/comentario.rb
 class Comentario < ActiveRecord::Base
    belongs_to :cancha
    #belongs_to :usuario
    belongs_to :usuario, :class_name => "Usuario", :foreign_key => "usuarios_id"
 end
 

app/models/distrito.rb
 class Distrito < ActiveRecord::Base
    has_many :locals
 end
 

app/models/local.rb
 class Local < ActiveRecord::Base
      self.table_name = "locales"
      
      
      belongs_to :usuario
      #belongs_to :distrito
      belongs_to :distrito, :class_name => "Distrito", :foreign_key => "distritos_id"
      has_many :canchas, :class_name => "Cancha", :foreign_key => "locales_id"
      has_many :servicios
      
      
      validates :nombre, presence: true
      validates :direccion, presence: true
      validates :distritos_id, presence: true
      
      
      accepts_nested_attributes_for :distrito
 end

app/models/persona.rb
 class Persona < ActiveRecord::Base
   belongs_to  :usuario, :class_name => "Usuario", :foreign_key => "usuarios_id"
   #has_many :usuario
   belongs_to :tipo_documento
     
   validates :tipo_documentos_id, presence: true
 end

app/models/publicidad.rb
 class Publicidad < ActiveRecord::Base
     self.table_name = "publicidades"
  
     belongs_to :usuario
     
     validates :titulo, presence: true
     validates :contenido, presence: true
     validates :fecha_inicio, presence: true
     validates :fecha_fin, presence: true
     validates :tarifa, presence: true
     validates :ubicacion, presence: true
 end

app/models/servicio.rb
 class Servicio < ActiveRecord::Base
     
     belongs_to :local, :class_name => "Local", :foreign_key => "locales_id"
     
     validates :nombre, presence: true
     validates :tipo_servicio, presence: true
     validates :importe_tarifa, presence: true
     validates :locales_id, presence: true
 end

app/models/tipo_documento.rb
 class TipoDocumento < ActiveRecord::Base
   has_many  :persona
 end

app/models/tipo_tarifa.rb
 class TipoTarifa < ActiveRecord::Base
      has_many :canchas
      
 end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_one :persona, :class_name => "Persona", :foreign_key => "usuarios_id"
  has_many  :locales
  has_many  :publicidades
  has_many :comentarios, :class_name => "Comentario", :foreign_key => "usuarios_id"
  
  
  accepts_nested_attributes_for :persona
end

app/helpers/alquiler_helper.rb
module AlquilerHelper
end

app/helpers/anuncio_helper.rb
module AnuncioHelper
end

app/helpers/cancha_helper.rb
module CanchaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/local_helper.rb
module LocalHelper
end

app/helpers/persona_helper.rb
module PersonaHelper
end

app/helpers/servicio_helper.rb
module ServicioHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <style>
    /* === GENERAL === */
    body{
    	padding-top: 50px;
    	background: url('/img/texture.png') top left repeat;
    }
    
    .wrap{
    	padding-top: 50px;
    	padding-bottom: 50px;
    }
    
    .header-section{
    	-webkit-font-smoothing: antialiased;
    	text-rendering: optimizelegibility;
    	text-align: center;
    }
    
    
    
    h1{
    	font-family: 'graduate', cursive;
    	/*font-family: 'Alegreya Sans SC', sans-serif;*/
    }
    
    h2{
    	font-family: 'pacifico', cursive;
    	/*font-family: 'Gloria Hallelujah', cursive;*/
    }
    
    /* === TITLE & ENROLL === */
    #title-enroll .jumbotron{
    	background: url('/img/mainBackground.png') 50% 0 no-repeat fixed;
    	-webkit-font-smoothing: antialiased;
    	text-rendering: optimizelegibility;
    	text-align: center;
    	color: white;
    }
    
    /* === BUSCADOR === */
    #buscador{
        background-color: #37454d;
    	  color: white;
    }
    
    #buscador-cancha{
        background-color: #FFFFFF;
    	  color: white;
    }
    
    
    /* === WHAT WILL YOU LEARN === */
    
    #what-learn{
    	text-align: center;
    }
    
    /* === COURSE TARGET === */
    
    #course-target{
    	background-color: #BF3E11;
    	color: white;
    }
    
    /* === COURSE FEATURES === */
    
    #course-features{
    	background-color: white;
    	text-align: center;
    }
    
    #course-features i{
    	margin-top: 20px;
    }
    
    /* === INSTRUCTOR === */
    
    #instructor .left-side{
    	text-align: center;
    }
    
    .badge.social{
    	background-color: #95A5A6;
    	font-size: 20px;
    	height: 35px;
    	width: 35px;
    	text-align: center;
    	line-height: 35px;
    	margin-top: 5px;
    	padding: 0;
    	-webkit-border-radius: 35px;
    	-moz-border-radius: 35px;
    	border-radius: 35px;
    	color: white;
    }
    .badge.social.twitter:hover{
    	background-color: #55ACEE;
    }
    .badge.social.linkedin:hover{
    	background-color: #4875B4;
    }
    .badge.social.blog:hover{
    	background-color: #26C281;
    }
    
    /* === PROMOTIONAL VIDEO === */
    
    #promo-video{
    	background: rgba(127,51,191, 0.7);
    	color: white;
    }
    
    /* === FOOTER === */
    
    #footer{
    	padding: 20px;
    	background-color: #22313F;
    	color: white;
    }
    
    #footer a{
    	color: #F5AB35;
    }
    
    #footer a:hover{
    	color: #F9690E;
    }
    
    /* ** lecture.html *** */
    
    /* === DISCUSSIONS === */
    
    #discussions{
    	background-color: white;
    }
    
    #discussions #btn-form, #discussions #btn-form-answer{
    	text-align: right;
    	margin-top: 5px;
    }
    
    /* ** admin_course.html *** */
    
    /* === ADMIN COURSE === */
    
    #admin-course .container{
    	background-color: white;
    	min-height: 600px;
    }
    
    #admin-course .panel-heading a{
    	color: white;
    }
    
    
    .box-btn {
      float: right;
      background: transparent;
      font-size: 30px;
      color: #4D4E56;
      font-weight: 300;
      cursor: pointer;
      border-radius: 2px;
      line-height: 0.5;
      border: none;
      outline: none;
    }
    .glyphicon {
      transition: color .3s linear;
    }  
    .box-btn .red {
      color: red;
    }
    
    a.redirect_page{
    	text-decoration: none;
        cursor: pointer;
    }
    
    dl, ol, ul {
      list-style: none;
      margin: 0;
      padding: 0;
  }
  
  .text {
    /*font-family: 'Bree Serif';*/
    color:#666;
    font-size:11px;
    margin-bottom:10px;
    padding:12px;
    background:#fff;
  }
  .breadcrumbs {
      position: relative;
      z-index: auto;
      border-bottom: 1px solid #E5E5E5;
      background-color: #F5F5F5;
      min-height: 41px;
      height:41px;
      line-height: 40px;
      padding: 0 12px 0 0;
  }
  .breadcrumb {
    background-color: transparent;
    line-height: 20px;
    margin: 0px 22px 0 12px;
    padding: 0;
    font-size: 13px;
    color: #333;
    border-radius: 0;
}

#map{height: 250px; }

#iFeatures {
  width: 100%;
  height: 73px;
  left: 0;
  bottom: 126px;
  /*background-color: rgba(0,39,62,.85);*/
}
.ticker {
  position: relative;
  top: 25%;
  left: 40px;
  right: 10px;
  bottom: 10%;
  overflow: hidden;
}

.ticker p {
  position: relative;
  top: 0;
  white-space: nowrap;
  width: auto;
  color: white;
  font-size: 20px;
}


</style>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  
  <link href="/jquery.bsPhotoGallery.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  
  
  

</head>
<body>
<!-- HEADER -->
<header>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">

      <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button><!-- .navbar-toggle -->

      <a class="navbar-brand" href="/home">
        <img src="/img/logo2.png" alt="BootIgniter">
      </a><!-- .navbar-brand -->
        
      </div><!-- .navbar-header -->

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if usuario_signed_in? %>
          <% if current_usuario.permission_level == 'D' || current_usuario.permission_level == 'A'%>
          <li><a href="/alquiler">Alquileres</a></li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mantenimiento <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/servicio">Mis Servicios</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/cancha">Mis Canchas</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/local">Mis Locales</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/publicidad">Anuncio</a></li>
            </ul>
          </li>
          <% end %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                <%= current_usuario.email %> <span class="caret"></span>
            </a>
            
            <ul class="dropdown-menu">
                <li><a href="/persona">Mis datos</a></li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to "Salir", destroy_usuario_session_path, method: :delete %>
                </li>
            </ul>
          </li>
            
          <% else %>
            <li>
              <%= link_to "Accede", new_usuario_session_path %>
            </li>
            <li>
              <%= link_to "Regístrate", new_usuario_registration_path %>  
            </li>
            
             
            
            <!--<li><a href="" data-toggle="modal" data-target="#modalLogin">Accede</a></li>
            <li><a href="" data-toggle="modal" data-target="#modalSingup">Regístrate</a></li>-->
          <% end %>
          
          
        </ul>
      </div><!-- .collapse -->

    </div><!-- .container -->
  </nav><!-- .navbar -->

</header>
<!-- END HEADER -->

<div class="alert alert-success hidden" id="message" role="alert">
      <div>            
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
           <span class="notice"><%= notice %></span>
           <span class="alert"><%= alert %></span>
      </div> 
</div>

<%= yield %>
</body>
</html>

<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>

<script type="text/javascript">
  $(function($) {
    $(document).on('click', '.box-btn', function(event) {
      $(this).find('.glyphicon').toggleClass('red').toggleClass('glyphicon-heart-empty glyphicon-heart');
    });
    
    var notice = '<%= notice %>';
    var alert = '<%= alert %>';
    
    
    
    if(notice != '' || alert != ''){
      $("#message").removeClass('hidden');
      $("#message").fadeTo(2000, 500).slideUp(500, function(){
          $("#message").slideUp(500);
      }); 
    }
    
    
    
    
    
   
  });
  function redirect(url) { url = url || ''; window.location.href = base_url(url);}
	function base_url(url) { url = url || ''; return url;}

</script>

<script type="text/javascript">
  $(function($) {
     $("#error_explanation").fadeTo(3000, 1000).slideUp(500, function(){
          $("#error_explanation").slideUp(500);
      }); 
  });
</script>
<script>
  $(document).ready(function() {
    var block_arr = $('.ticker li p').map(function() { return $(this).get(0);}).toArray();
    console.log(block_arr);
    
    var ticker_item = $(block_arr[0]);
    $(".ticker").html(ticker_item);
    var ticker_width = $(".ticker").width();
    var text_x = ticker_width;
      
    console.log(block_arr.indexOf(ticker_item.get(0)));
    console.log(block_arr.length);
  
    scroll_ticker = function() {    
      text_x--;
      ticker_item.css("left", text_x);
      if (text_x < -1 * ticker_item.width()) {
        ticker_item = $(block_arr[(block_arr.indexOf(ticker_item.get(0)) + 1 == block_arr.length) ? 0 : block_arr.indexOf(ticker_item.get(0)) + 1]);
        ticker_item.css("left", text_x);
        $(".ticker").html(ticker_item);
        text_x = ticker_width;
      }
    }
    setInterval(scroll_ticker, 5);
  });
</script>